import fs from "fs";
import path from "path";
import { BusinessTenant } from "../src/types/tenant";

const TENANTS_DIR = path.resolve(process.cwd(), "tenants");
const SEED_OUTPUT = path.resolve(process.cwd(), "supabase", "seed.sql");

export function generateSeedAndPublish(): void {
  console.log("--> Starting tenant publish process...");

  if (!fs.existsSync(TENANTS_DIR)) {
    console.error("ERROR: No tenants directory found.");
    process.exit(1);
  }

  const entries = fs.readdirSync(TENANTS_DIR, { withFileTypes: true });
  const tenantDirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);

  const tenants: BusinessTenant[] = [];

  for (const dir of tenantDirs) {
    const jsonPath = path.join(TENANTS_DIR, dir, "business.json");
    if (fs.existsSync(jsonPath)) {
      const data = JSON.parse(fs.readFileSync(jsonPath, "utf-8")) as BusinessTenant;
      tenants.push(data);
    }
  }

  // Ensure supabase directory exists
  fs.mkdirSync(path.dirname(SEED_OUTPUT), { recursive: true });

  const sqlStatements: string[] = [
    "-- Generated by scripts/tenant-publish.ts",
    "-- Idempotent upsert of all verified tenants and resources",
    "BEGIN;",
    "",
  ];

  for (const t of tenants) {
    const escapedConfig = JSON.stringify(t).replace(/'/g, "''");
    sqlStatements.push(`
INSERT INTO public.tenants (slug, name, city, phone, config, active, created_at, updated_at)
VALUES (
  '${t.slug}',
  '${t.name.replace(/'/g, "''")}',
  '${t.city.replace(/'/g, "''")}',
  '${t.phone.replace(/'/g, "''")}',
  '${escapedConfig}'::jsonb,
  true,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  phone = EXCLUDED.phone,
  config = EXCLUDED.config,
  updated_at = NOW();
`);

    // Resources (Surveyors)
    for (const s of t.surveyors) {
      sqlStatements.push(`
INSERT INTO public.resources (id, tenant_slug, name, role, phone, active)
VALUES (
  '${s.id}',
  '${t.slug}',
  '${s.name.replace(/'/g, "''")}',
  '${s.role.replace(/'/g, "''")}',
  '${s.phone.replace(/'/g, "''")}',
  ${s.active}
)
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  active = EXCLUDED.active;
`);
    }
  }

  sqlStatements.push("COMMIT;");
  fs.writeFileSync(SEED_OUTPUT, sqlStatements.join("\n"), "utf-8");

  console.log(`[OK] Successfully published ${tenants.length} tenants into SQL seed:`);
  console.log(`  -> ${SEED_OUTPUT}`);
  console.log("Ready for deployment to Supabase Postgres.");
}

if (process.argv[1]?.endsWith("tenant-publish.ts")) {
  generateSeedAndPublish();
}
